#ifndef _libets_h_
#define _libets_h_

#define ETS_PORT 2554

#define ETS_RETURN_BEGIN 5
#define ETS_RETURN_OK  (ETS_RETURN_BEGIN+0)
#define ETS_RETURN_FAILED  (ETS_RETURN_BEGIN+1)
#define ETS_RETURN_REDIRECTION  (ETS_RETURN_BEGIN+2)
#define ETS_RETURN_NOTFOUND  (ETS_RETURN_BEGIN+3)
#define ETS_RETURN_END 9

#define ETS_COMMAND_BEGIN 10
#define ETS_CONNECT  (ETS_COMMAND_BEGIN+0)
#define ETS_JOIN	 (ETS_COMMAND_BEGIN+1)
#define ETS_CLOSE	 (ETS_COMMAND_BEGIN+2)
#define ETS_PLAY	 (ETS_COMMAND_BEGIN+3)
#define ETS_PAUSE	 (ETS_COMMAND_BEGIN+4)
#define ETS_NOP		 (ETS_COMMAND_BEGIN+5)
#define ETS_CONNECT_CDN		 (ETS_COMMAND_BEGIN+6)
#define ETS_BROADCAST	 (ETS_COMMAND_BEGIN+10)
#define ETS_COMMAND_END 59

#define ETS_VIDEO_BEGIN  60
#define ETS_H263   (ETS_VIDEO_BEGIN+0)
#define ETS_H264   (ETS_VIDEO_BEGIN+1)
#define ETS_H265   (ETS_VIDEO_BEGIN+2)
#define ETS_MP4V_ES   (ETS_VIDEO_BEGIN+3)
#define ETS_MPEG1   (ETS_VIDEO_BEGIN+4)
#define ETS_MJPEG   (ETS_VIDEO_BEGIN+5)
#define ETS_VIDEO_END  89

#define ETS_AUDIO_BEGIN  90
#define ETS_AAC		(ETS_AUDIO_BEGIN+0)
#define ETS_AMRNB   (ETS_AUDIO_BEGIN+1)
#define ETS_AMRWB   (ETS_AUDIO_BEGIN+2)
#define ETS_PCM     (ETS_AUDIO_BEGIN+3)
#define ETS_AUDIO_END  119

#define ETS_TEXT_BEGIN  120
#define ETS_TEXT		(ETS_TEXT_BEGIN+0)
#define ETS_RAWGPS		(ETS_TEXT_BEGIN+1)
#define ETS_LBS   (ETS_TEXT_BEGIN+2)
#define ETS_LRC   (ETS_TEXT_BEGIN+3)
#define ETS_MSG     (ETS_TEXT_BEGIN+4)
#define ETS_TEXT_END  139


#endif








